
//auth

export const LOGOUT = 'LOGOUT'
export const LOGIN = 'LOGIN'
//profile-manager
export const GET_PROFILE = 'GET_PROFILE'
//evaluation
export const GET_LIST_EVALUATION = 'GET_LIST_EVALUATION'
export const GET_ALL_EVALUATION = 'GET_ALL_EVALUATION'
export const GET_ALL_STATUS = 'GET_ALL_STATUS'
export const GET_DETAIL_EVALUATION = 'GET_DETAIL_EVALUATION'
export const GET_COMPETENCIES = 'GET_COMPETENCIES'
export const GET_AVAILABLE_PERIOD = 'GET_AVAILABLE_PERIOD'
export const GET_DETAIL_PERIOD = 'GET_DETAIL_PERIOD'
export const SAVE_EVALUATION = 'SAVE_EVALUATION'
export const GET_CURRENT_STATUS = 'GET_CURRENT_STATUS'
export const GET_COMPETENCY_DETAIL = 'GET_COMPETENCY_DETAIL'

//member
export const GET_LIST_MEMBER_EVALUATION = 'GET_LIST_MEMBER_EVALUATION'
export const GET_LIST_ASSOCIATES = 'GET_LIST_ASSOCIATES'
export const GET_ALL_POSITION = 'GET_ALL_POSITION'

//associate
export const SAVE_ASSOCIATE = 'SAVE_ASSOCIATE'

//period
export const GET_ALL_PERIOD_ADMIN = 'GET_ALL_PERIOD_ADMIN'
export const SAVE_PERIOD = 'SAVE_PERIOD'
export const GET_DETAIL_PERIOD_ADMIN = 'GET_DETAIL_PERIOD_ADMIN'

//competency-position
export const GET_ALL_COMPETENCY_POSITION = 'GET_ALL_COMPETENCY_POSITON'
export const GET_ALL_COMPETENCY = 'GET_ALL_COMPETENCY'
export const UPDATE_COMPETENCY_POSITION = 'UPDATE_COMPETENCY_POSITION'

//competency
export const GET_ALL_COMPETENCY_ADMIN = 'GET_ALL_COMPETENCY_ADMIN'
export const GET_ALL_COMPETENCY_TYPE_ADMIN = 'GET_ALL_COMPETENCY_TYPE_ADMIN'
export const SAVE_COMPETENCY_ADMIN = 'SAVE_COMPETENCY_ADMIN'
export const GET_DETAIL_COMPETENCY_ADMIN = 'GET_DETAIL_COMPETENCY_ADMIN'